# Generated by Django 4.0.4 on 2022-04-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_remove_details_userid_remove_education_userid_and_more'),
        ('prodetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='slink',
        ),
        migrations.RemoveField(
            model_name='family',
            name='userid',
        ),
        migrations.AddField(
            model_name='siblings',
            name='slink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodetail.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siblings',
            name='userid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel'),
            preserve_default=False,
        ),
    ]
