# Generated by Django 4.0.4 on 2022-04-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodetail', '0002_remove_family_slink_remove_family_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siblings',
            name='slink',
        ),
    ]
