# Generated by Django 4.0.4 on 2022-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodetail', '0003_remove_siblings_slink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='salary',
            field=models.FloatField(),
        ),
    ]
