# Generated by Django 4.0.4 on 2022-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodetail', '0004_alter_occupation_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='flink',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='llink',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='ylink',
            field=models.CharField(max_length=30),
        ),
    ]
