# Generated by Django 4.0.4 on 2022-04-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='siblings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('oname', models.CharField(max_length=50)),
                ('statusm', models.CharField(choices=[['Married', 'Married'], ['UnMarried', 'UnMarried']], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='profilelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flink', models.URLField()),
                ('llink', models.URLField()),
                ('ylink', models.URLField()),
                ('phone', models.BigIntegerField()),
                ('alphone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2)),
                ('company', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('focc', models.CharField(max_length=50)),
                ('fphone', models.BigIntegerField()),
                ('mname', models.CharField(max_length=50)),
                ('mocc', models.CharField(max_length=50)),
                ('slink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.siblings')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highedu', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('time', models.TimeField()),
                ('aob', models.CharField(max_length=50)),
                ('rasi', models.CharField(choices=[['Aries', 'Aries'], ['Taurus', 'Taurus'], ['Gemini', 'Gemini'], ['Cancer', 'Cancer'], ['Leo', 'Leo'], ['Virgo', 'Virgo'], ['Libra', 'Libra'], ['Scorpio', 'Scorpio'], ['Saggitarius', 'Saggitarius'], ['Capricorn', 'Capricorn'], ['Aquarius', 'Aquarius'], ['Pisces', 'Pisces']], max_length=20)),
                ('nakshatra', models.CharField(max_length=15)),
                ('padha', models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4']], max_length=3)),
                ('height', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='profilepic/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdno', models.CharField(max_length=20)),
                ('streetname', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
    ]
