# Generated by Django 4.0.4 on 2022-04-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_siblings_profilelink_occupation_family_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='education',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='family',
            name='slink',
        ),
        migrations.RemoveField(
            model_name='family',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='profilelink',
            name='userid',
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='family',
        ),
        migrations.DeleteModel(
            name='occupation',
        ),
        migrations.DeleteModel(
            name='profilelink',
        ),
        migrations.DeleteModel(
            name='siblings',
        ),
    ]
